# Generated by Django 3.0.4 on 2020-06-23 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Arte y Humanidades', 'Arte y Humanidades'), ('Belleza y Moda', 'Belleza y Moda'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Comida', 'Comida'), ('Deportes', 'Deportes'), ('Informatica', 'Informatica'), ('Hogar', 'Hogar'), ('Mascotas', 'Mascotas'), ('Medio Ambiente', 'Medio Ambiente'), ('Politica', 'Politica'), ('Salud', 'Salud'), ('Entretenimiento', 'Entretenimiento'), ('Restaurantes', 'Restaurantes'), ('Sociedad y Cultura', 'Sociedad y Cultura'), ('Viajes', 'Viajes'), ('Educacion', 'Educacion')], default='Arte y Humanidades', max_length=25)),
                ('question', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_respond', to=settings.AUTH_USER_MODEL)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_answer', to='pregunta.Pregunta')),
            ],
        ),
    ]
